steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=quay.io/pauljwilliams1976/spinnaker-demo', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'quay.io/pauljwilliams1976/spinnaker-demo']
images: ['gcr.io/$PROJECT_ID/spring-boot']